defaults: &defaults
  docker:
    - image: quay.io/pantheon-public/terminus-plugin-test:4.x-php8.2
  working_directory: ~/work/terminus_pantheor_plugin
  environment:
    BASH_ENV: ~/.bashrc
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    TERM: dumb

version: 2
jobs:
    test:
        <<: *defaults
        steps:
            - checkout
            - run:
                name: Disabled
                command: echo 'This project is deprecated; tests are disabled.'

workflows:
  version: 2
  build_test:
    jobs:
      - test
